version: "3.6"
services:
  mainnet-peer:
    image: proximax/proximax-sirius-chain:v1.8.0-bullseye
    ports:
      - 7903:7903
      - 7902:7902
      - 7900:7900
      - 7901:7901
    volumes:
      - ./:/chainconfig
      - ./data:/data:rw
      - ./logs:/logs:rw
    restart: on-failure:3
    